name: Rails test

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

env:
  RAILS_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      matrix:
        ruby-version: ['3.2.0']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Create development_secret.txt
      env:
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      run: |
        touch tmp/development_secret.txt
        echo -n $SECRET_KEY_BASE > tmp/development_secret.txt
    - name: Precompile assets
      run: bundle exec rake assets:precompile
    - name: Run tests
      run: bundle exec rails test
    - name: Upload coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ github.token }}